SELECT DISTINCT
	PERCENTILE_CONT(0.05) WITHIN GROUP (ORDER BY price) OVER () as p5,
	PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY price) OVER () as p25,
	PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY price) OVER () as p50,
	PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY price) OVER () as p75,
	PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY price) OVER () as p95
FROM Listings;